// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbhlwczocwyumxvnrhgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaGx3Y3pvY3d5dW14dm5yaGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTkzMzMsImV4cCI6MjA2MDM5NTMzM30.BbZcTb_p9o-OG2YbxIlHNTTGJHTNscxVrmDjau-AMI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);